%YAML 1.2
---
host: wp200.hostgator.com.br
porta: 465
usuario: robo@conectasolucoes.com.br
senha: gAAAAABiVD0_CIWbkzojWu5aWGiz_9e6JVXhiie7iTNb03uqfhhIKxJ9NvL6PQmuGUMp3amUrKA-FDzmW8psjJ1oICQJ3eLDIA==
...
